version: 2.1

jobs:
  build:
    docker:
      - image: php:7.4-apache
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: equal
    working_directory: /var/www/html
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get -y install git libzip-dev
            docker-php-ext-install pdo pdo_mysql mysqli zip
            docker-php-ext-enable mysqli
      - run:
          name: Clone equal repository
          command: git clone https://github.com/equalframework/equal.git
      - run:
          name: List Branches Remote
          command: git ls-remote --heads https://github.com/equalframework/equal.git
      #- run: git config --global --add safe.directory /var/www/html
      - run:
          name: Copy files to the working directory
          command: |
            cd equal/
            git checkout dev-2.0
            cd ..
            cp -r equal/* /var/www/html/
      - run: ls -lah
      - run:
          name: Set permissions for 'run.php'
          command: chmod 755 run.php
      - run: ls -lah
      - run:
          name: Verify the presence and correct Access Rights of mandatory directories
          command: php run.php --do=test_fs-consistency
      - run:
          name: Verifying the Connectivity to the DBMS Service
          command: php run.php --do=test_db-connectivity
      - run:
          name: Creating an Empty Database
          command: php run.php --do=init_db
      - run:
          name: Initializing core package with Demo Data
          command: php run.php --do=init_package --package=core --import=true
      - run:
          name: Running Test Units for the Core Package
          command: php run.php --do=test_package --package=core
      - run:
          name: Clone projectFlow repository
          command: git clone https://github.com/alexandraYesbabylon/projectFlow.git projectFlow
      - run: ls -lah
      - run:
          name: Moving projectFlow  to packages
          command: mv projectFlow packages
      - run:
          name: Initializing projectFlow package with Demo Data
          command: php run.php --do=init_package --package=projectFlow --import=true
      - run:
          name: Running Test Units for the ProjectFlow Package
          command: php run.php --do=test_package --package=projectFlow
      - run:
          name: List of existing employees
          command: php run.php --get=model_collect --entity=projectFlow\\Employee
      - run:
          name: Install MariaDb Client
          command: |
            apt-get -y install mariadb-client
            mysql --version;
workflows:
  build_and_test:
    jobs:
      - build
